### ISSUE TITLE
Missing results

### ISSUE THREAD

**Issue by MirzaAtharBaig** [rossmacarthur/mawg#1]
Hi, 

First of all let me tell you this is a really cool idea and project. You did great. Can u share your simulation and implementation results. Also It would be great if you can make a HOW TO guide to get those results. Thanks

**Comment by rossmacarthur** [comment]
Hi @AtharBaig0027,

I will see if I can upload the the thesis write up somewhere, and add a link to the README. Will think about adding a HOW TO guide, but I don't think I will get around to it.
